version: '3'
services:
    api-gateway:
        build: ./api-gateway
        container_name: api-gateway
        ports: 
            - "7000:5000"
        networks:
            - "flamingo-network"

    customer-db:
        image: postgres
        container_name: customer-db
        environment:
            POSTGRES_PASSWORD: Abc.12345
            POSTGRES_DB: customer_db
            NODE_ENV: development
        networks: 
            - "flamingo-network"
        volumes:
            - ./customer-db/db-scripts:/docker-entrypoint-initdb.d

    costumer-service:
        build: 
            context: ./customer-service
            args:
                POSTGRES_PASSWORD: Abc.12345
                POSTGRES_DB: customer_db

        container_name: customer-service
        networks:
            - "flamingo-network" 

    email-service:
        build: ./email-service
        container_name: email-service
        networks:
            - "flamingo-network"
    
    log-service:
        build: ./log-service
        container_name: log-service
        networks:
            - "flamingo-network"

    order-service:
        image: mongo
        build: ./order-service
        container_name: order-service
        networks: 
            - "flamingo-network"


    message-broker:
        image: rabbitmq
        build: ./order-service
        container_name: message-broker
        networks:
            - "flamingo-network"

networks:
    flamingo-network:
        driver: bridge
